language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'sailor-translate' ]; then cd .. && eval "mv $currentfolder sailor-translate" && cd sailor-translate; fi
